### ISSUE TITLE
Expected Distribution Method

### ISSUE THREAD

**Issue by daryllabar** [Power-Platform-Patterns-and-Practices/Dataverse.Sdk.Extensions#13]
We've had some talk about this in Slack, but what is the expected method of incorporating this logic into other repositories?

**Comment by BetimBeja** [comment]
In PR #8 I created a nuspec for a NuGet package which contains a .targets to reference the shared project (also included as source code in the NuGet package).

**Comment by daryllabar** [comment]
So a source only Nuget package?  Awesome!

**Comment by jordimontana82** [comment]
I use source nuget packages quite a lot for the last couple of months too :)  

Also, is there a link to the Slack workspace? :stuck_out_tongue:
